"""Русские названия 601 класса Open Images V7 (модели yolov8*-oiv7.pt)."""

OIV7_RU = {
    "Accordion": "Аккордеон", "Adhesive tape": "Скотч", "Aircraft": "Летательный аппарат", "Airplane": "Самолёт",
    "Alarm clock": "Будильник", "Alpaca": "Альпака", "Ambulance": "Скорая помощь", "Animal": "Животное",
    "Ant": "Муравей", "Antelope": "Антилопа", "Apple": "Яблоко", "Armadillo": "Броненосец",
    "Artichoke": "Артишок", "Auto part": "Автозапчасть", "Axe": "Топор", "Backpack": "Рюкзак",
    "Bagel": "Бублик", "Baked goods": "Выпечка", "Balance beam": "Гимнастическое бревно", "Ball": "Мяч",
    "Balloon": "Воздушный шар", "Banana": "Банан", "Band-aid": "Пластырь", "Banjo": "Банджо",
    "Barge": "Баржа", "Barrel": "Бочка", "Baseball bat": "Бейсбольная бита", "Baseball glove": "Бейсбольная перчатка",
    "Bat (Animal)": "Летучая мышь", "Bathroom accessory": "Аксессуар для ванной", "Bathroom cabinet": "Шкафчик для ванной",
    "Bathtub": "Ванна", "Beaker": "Мензурка", "Bear": "Медведь", "Bed": "Кровать", "Bee": "Пчела",
    "Beehive": "Улей", "Beer": "Пиво", "Beetle": "Жук", "Bell pepper": "Болгарский перец", "Belt": "Ремень",
    "Bench": "Скамейка", "Bicycle": "Велосипед", "Bicycle helmet": "Велошлем", "Bicycle wheel": "Колесо велосипеда",
    "Bidet": "Биде", "Billboard": "Рекламный щит", "Billiard table": "Бильярдный стол", "Binoculars": "Бинокль",
    "Bird": "Птица", "Blender": "Блендер", "Blue jay": "Голубая сойка", "Boat": "Лодка", "Bomb": "Бомба",
    "Book": "Книга", "Bookcase": "Книжный шкаф", "Boot": "Ботинок", "Bottle": "Бутылка",
    "Bottle opener": "Открывалка", "Bow and arrow": "Лук и стрелы", "Bowl": "Миска",
    "Bowling equipment": "Снаряжение для боулинга", "Box": "Коробка", "Boy": "Мальчик", "Brassiere": "Бюстгальтер",
    "Bread": "Хлеб", "Briefcase": "Портфель", "Broccoli": "Брокколи", "Bronze sculpture": "Бронзовая скульптура",
    "Brown bear": "Бурый медведь", "Building": "Здание", "Bull": "Бык", "Burrito": "Буррито", "Bus": "Автобус",
    "Bust": "Бюст", "Butterfly": "Бабочка", "Cabbage": "Капуста", "Cabinetry": "Шкафы", "Cake": "Торт",
    "Cake stand": "Подставка для торта", "Calculator": "Калькулятор", "Camel": "Верблюд", "Camera": "Фотоаппарат",
    "Can opener": "Консервный нож", "Canary": "Канарейка", "Candle": "Свеча", "Candy": "Конфета", "Cannon": "Пушка",
    "Canoe": "Каноэ", "Cantaloupe": "Дыня-канталупа", "Car": "Автомобиль", "Carnivore": "Хищник",
    "Carrot": "Морковь", "Cart": "Тележка", "Cassette deck": "Кассетная дека", "Castle": "Замок", "Cat": "Кошка",
    "Cat furniture": "Домик для кошки", "Caterpillar": "Гусеница", "Cattle": "Крупный рогатый скот",
    "Ceiling fan": "Потолочный вентилятор", "Cello": "Виолончель", "Centipede": "Сороконожка", "Chainsaw": "Бензопила",
    "Chair": "Стул", "Cheese": "Сыр", "Cheetah": "Гепард", "Chest of drawers": "Комод", "Chicken": "Курица",
    "Chime": "Колокольчики", "Chisel": "Стамеска", "Chopsticks": "Палочки для еды", "Christmas tree": "Новогодняя ёлка",
    "Clock": "Часы", "Closet": "Гардероб", "Clothing": "Одежда", "Coat": "Пальто", "Cocktail": "Коктейль",
    "Cocktail shaker": "Шейкер", "Coconut": "Кокос", "Coffee": "Кофе", "Coffee cup": "Кофейная чашка",
    "Coffee table": "Журнальный столик", "Coffeemaker": "Кофеварка", "Coin": "Монета", "Common fig": "Инжир",
    "Common sunflower": "Подсолнух", "Computer keyboard": "Клавиатура", "Computer monitor": "Монитор",
    "Computer mouse": "Компьютерная мышь", "Container": "Контейнер", "Convenience store": "Магазин у дома",
    "Cookie": "Печенье", "Cooking spray": "Кулинарный спрей", "Corded phone": "Проводной телефон",
    "Cosmetics": "Косметика", "Couch": "Диван", "Countertop": "Столешница", "Cowboy hat": "Ковбойская шляпа",
    "Crab": "Краб", "Cream": "Крем", "Cricket ball": "Мяч для крикета", "Crocodile": "Крокодил",
    "Croissant": "Круассан", "Crown": "Корона", "Crutch": "Костыль", "Cucumber": "Огурец", "Cupboard": "Буфет",
    "Curtain": "Штора", "Cutting board": "Разделочная доска", "Dagger": "Кинжал", "Dairy Product": "Молочный продукт",
    "Deer": "Олень", "Desk": "Письменный стол", "Dessert": "Десерт", "Diaper": "Подгузник", "Dice": "Игральные кости",
    "Digital clock": "Электронные часы", "Dinosaur": "Динозавр", "Dishwasher": "Посудомоечная машина", "Dog": "Собака",
    "Dog bed": "Лежанка для собаки", "Doll": "Кукла", "Dolphin": "Дельфин", "Door": "Дверь",
    "Door handle": "Дверная ручка", "Doughnut": "Пончик", "Dragonfly": "Стрекоза", "Drawer": "Выдвижной ящик",
    "Dress": "Платье", "Drill (Tool)": "Дрель", "Drink": "Напиток", "Drinking straw": "Трубочка для напитков",
    "Drum": "Барабан", "Duck": "Утка", "Dumbbell": "Гантель", "Eagle": "Орёл", "Earrings": "Серьги",
    "Egg (Food)": "Яйцо", "Elephant": "Слон", "Envelope": "Конверт", "Eraser": "Ластик", "Face powder": "Пудра",
    "Facial tissue holder": "Салфетница", "Falcon": "Сокол", "Fashion accessory": "Модный аксессуар",
    "Fast food": "Фастфуд", "Fax": "Факс", "Fedora": "Фетровая шляпа", "Filing cabinet": "Картотечный шкаф",
    "Fire hydrant": "Пожарный гидрант", "Fireplace": "Камин", "Fish": "Рыба", "Flag": "Флаг", "Flashlight": "Фонарик",
    "Flower": "Цветок", "Flowerpot": "Цветочный горшок", "Flute": "Флейта", "Flying disc": "Фрисби", "Food": "Еда",
    "Food processor": "Кухонный комбайн", "Football": "Мяч для американского футбола",
    "Football helmet": "Шлем для американского футбола", "Footwear": "Обувь", "Fork": "Вилка", "Fountain": "Фонтан",
    "Fox": "Лиса", "French fries": "Картофель фри", "French horn": "Валторна", "Frog": "Лягушка", "Fruit": "Фрукт",
    "Frying pan": "Сковорода", "Furniture": "Мебель", "Garden Asparagus": "Спаржа", "Gas stove": "Газовая плита",
    "Giraffe": "Жираф", "Girl": "Девочка", "Glasses": "Очки", "Glove": "Перчатка", "Goat": "Коза",
    "Goggles": "Защитные очки", "Goldfish": "Золотая рыбка", "Golf ball": "Мяч для гольфа",
    "Golf cart": "Гольф-кар", "Gondola": "Гондола", "Goose": "Гусь", "Grape": "Виноград", "Grapefruit": "Грейпфрут",
    "Grinder": "Кофемолка", "Guacamole": "Гуакамоле", "Guitar": "Гитара", "Hair dryer": "Фен",
    "Hair spray": "Лак для волос", "Hamburger": "Гамбургер", "Hammer": "Молоток", "Hamster": "Хомяк",
    "Hand dryer": "Сушилка для рук", "Handbag": "Сумка", "Handgun": "Пистолет", "Harbor seal": "Тюлень",
    "Harmonica": "Губная гармошка", "Harp": "Арфа", "Harpsichord": "Клавесин", "Hat": "Шляпа",
    "Headphones": "Наушники", "Heater": "Обогреватель", "Hedgehog": "Ёж", "Helicopter": "Вертолёт",
    "Helmet": "Шлем", "High heels": "Туфли на каблуке", "Hiking equipment": "Туристическое снаряжение",
    "Hippopotamus": "Бегемот", "Home appliance": "Бытовая техника", "Honeycomb": "Соты",
    "Horizontal bar": "Турник", "Horse": "Лошадь", "Hot dog": "Хот-дог", "House": "Дом",
    "Houseplant": "Комнатное растение", "Human arm": "Рука", "Human beard": "Борода", "Human body": "Тело человека",
    "Human ear": "Ухо", "Human eye": "Глаз", "Human face": "Лицо", "Human foot": "Ступня", "Human hair": "Волосы",
    "Human hand": "Кисть руки", "Human head": "Голова", "Human leg": "Нога", "Human mouth": "Рот",
    "Human nose": "Нос", "Humidifier": "Увлажнитель", "Ice cream": "Мороженое", "Indoor rower": "Гребной тренажёр",
    "Infant bed": "Детская кроватка", "Insect": "Насекомое", "Invertebrate": "Беспозвоночное", "Ipod": "iPod",
    "Isopod": "Равноногий рачок", "Jacket": "Куртка", "Jacuzzi": "Джакузи", "Jaguar (Animal)": "Ягуар",
    "Jeans": "Джинсы", "Jellyfish": "Медуза", "Jet ski": "Гидроцикл", "Jug": "Кувшин", "Juice": "Сок",
    "Kangaroo": "Кенгуру", "Kettle": "Чайник", "Kitchen & dining room table": "Обеденный стол",
    "Kitchen appliance": "Кухонная техника", "Kitchen knife": "Кухонный нож", "Kitchen utensil": "Кухонная утварь",
    "Kitchenware": "Посуда", "Kite": "Воздушный змей", "Knife": "Нож", "Koala": "Коала", "Ladder": "Лестница-стремянка",
    "Ladle": "Половник", "Ladybug": "Божья коровка", "Lamp": "Лампа", "Land vehicle": "Наземный транспорт",
    "Lantern": "Фонарь", "Laptop": "Ноутбук", "Lavender (Plant)": "Лаванда", "Lemon": "Лимон", "Leopard": "Леопард",
    "Light bulb": "Лампочка", "Light switch": "Выключатель", "Lighthouse": "Маяк", "Lily": "Лилия",
    "Limousine": "Лимузин", "Lion": "Лев", "Lipstick": "Помада", "Lizard": "Ящерица", "Lobster": "Омар",
    "Loveseat": "Двухместный диван", "Luggage and bags": "Багаж и сумки", "Lynx": "Рысь", "Magpie": "Сорока",
    "Mammal": "Млекопитающее", "Man": "Мужчина", "Mango": "Манго", "Maple": "Клён", "Maracas": "Маракасы",
    "Marine invertebrates": "Морские беспозвоночные", "Marine mammal": "Морское млекопитающее",
    "Measuring cup": "Мерный стакан", "Mechanical fan": "Вентилятор", "Medical equipment": "Медицинское оборудование",
    "Microphone": "Микрофон", "Microwave oven": "Микроволновка", "Milk": "Молоко", "Miniskirt": "Мини-юбка",
    "Mirror": "Зеркало", "Missile": "Ракета (оружие)", "Mixer": "Миксер", "Mixing bowl": "Миска для смешивания",
    "Mobile phone": "Мобильный телефон", "Monkey": "Обезьяна", "Moths and butterflies": "Бабочки и мотыльки",
    "Motorcycle": "Мотоцикл", "Mouse": "Мышь", "Muffin": "Маффин", "Mug": "Кружка", "Mule": "Мул",
    "Mushroom": "Гриб", "Musical instrument": "Музыкальный инструмент", "Musical keyboard": "Синтезатор",
    "Nail (Construction)": "Гвоздь", "Necklace": "Ожерелье", "Nightstand": "Прикроватная тумбочка", "Oboe": "Гобой",
    "Office building": "Офисное здание", "Office supplies": "Канцтовары", "Orange": "Апельсин",
    "Organ (Musical Instrument)": "Орган", "Ostrich": "Страус", "Otter": "Выдра", "Oven": "Духовка", "Owl": "Сова",
    "Oyster": "Устрица", "Paddle": "Весло", "Palm tree": "Пальма", "Pancake": "Блин", "Panda": "Панда",
    "Paper cutter": "Резак для бумаги", "Paper towel": "Бумажное полотенце", "Parachute": "Парашют",
    "Parking meter": "Паркомат", "Parrot": "Попугай", "Pasta": "Паста", "Pastry": "Пирожное", "Peach": "Персик",
    "Pear": "Груша", "Pen": "Ручка", "Pencil case": "Пенал", "Pencil sharpener": "Точилка", "Penguin": "Пингвин",
    "Perfume": "Духи", "Person": "Человек", "Personal care": "Средства гигиены",
    "Personal flotation device": "Спасательный жилет", "Piano": "Пианино", "Picnic basket": "Корзина для пикника",
    "Picture frame": "Рамка для фото", "Pig": "Свинья", "Pillow": "Подушка", "Pineapple": "Ананас",
    "Pitcher (Container)": "Графин", "Pizza": "Пицца", "Pizza cutter": "Нож для пиццы", "Plant": "Растение",
    "Plastic bag": "Пластиковый пакет", "Plate": "Тарелка", "Platter": "Блюдо",
    "Plumbing fixture": "Сантехника", "Polar bear": "Белый медведь", "Pomegranate": "Гранат", "Popcorn": "Попкорн",
    "Porch": "Крыльцо", "Porcupine": "Дикобраз", "Poster": "Плакат", "Potato": "Картофель",
    "Power plugs and sockets": "Вилки и розетки", "Pressure cooker": "Скороварка", "Pretzel": "Крендель",
    "Printer": "Принтер", "Pumpkin": "Тыква", "Punching bag": "Боксёрская груша", "Rabbit": "Кролик",
    "Raccoon": "Енот", "Racket": "Ракетка", "Radish": "Редис", "Ratchet (Device)": "Трещотка (ключ)",
    "Raven": "Ворон", "Rays and skates": "Скаты", "Red panda": "Красная панда", "Refrigerator": "Холодильник",
    "Remote control": "Пульт", "Reptile": "Рептилия", "Rhinoceros": "Носорог", "Rifle": "Винтовка",
    "Ring binder": "Папка-регистратор", "Rocket": "Ракета", "Roller skates": "Роликовые коньки", "Rose": "Роза",
    "Rugby ball": "Мяч для регби", "Ruler": "Линейка", "Salad": "Салат",
    "Salt and pepper shakers": "Солонка и перечница", "Sandal": "Сандалия", "Sandwich": "Сэндвич",
    "Saucer": "Блюдце", "Saxophone": "Саксофон", "Scale": "Весы", "Scarf": "Шарф", "Scissors": "Ножницы",
    "Scoreboard": "Табло", "Scorpion": "Скорпион", "Screwdriver": "Отвёртка", "Sculpture": "Скульптура",
    "Sea lion": "Морской лев", "Sea turtle": "Морская черепаха", "Seafood": "Морепродукты", "Seahorse": "Морской конёк",
    "Seat belt": "Ремень безопасности", "Segway": "Сегвей", "Serving tray": "Поднос",
    "Sewing machine": "Швейная машина", "Shark": "Акула", "Sheep": "Овца", "Shelf": "Полка",
    "Shellfish": "Моллюски", "Shirt": "Рубашка", "Shorts": "Шорты", "Shotgun": "Дробовик", "Shower": "Душ",
    "Shrimp": "Креветка", "Sink": "Раковина", "Skateboard": "Скейтборд", "Ski": "Лыжа", "Skirt": "Юбка",
    "Skull": "Череп", "Skunk": "Скунс", "Skyscraper": "Небоскрёб", "Slow cooker": "Мультиварка", "Snack": "Закуска",
    "Snail": "Улитка", "Snake": "Змея", "Snowboard": "Сноуборд", "Snowman": "Снеговик", "Snowmobile": "Снегоход",
    "Snowplow": "Снегоуборщик", "Soap dispenser": "Дозатор мыла", "Sock": "Носок", "Sofa bed": "Диван-кровать",
    "Sombrero": "Сомбреро", "Sparrow": "Воробей", "Spatula": "Лопатка", "Spice rack": "Полка для специй",
    "Spider": "Паук", "Spoon": "Ложка", "Sports equipment": "Спортивный инвентарь",
    "Sports uniform": "Спортивная форма", "Squash (Plant)": "Кабачок", "Squid": "Кальмар", "Squirrel": "Белка",
    "Stairs": "Лестница", "Stapler": "Степлер", "Starfish": "Морская звезда",
    "Stationary bicycle": "Велотренажёр", "Stethoscope": "Стетоскоп", "Stool": "Табурет", "Stop sign": "Знак «Стоп»",
    "Strawberry": "Клубника", "Street light": "Уличный фонарь", "Stretcher": "Носилки", "Studio couch": "Тахта",
    "Submarine": "Подводная лодка", "Submarine sandwich": "Сэндвич-сабмарина", "Suit": "Костюм",
    "Suitcase": "Чемодан", "Sun hat": "Панама", "Sunglasses": "Солнцезащитные очки", "Surfboard": "Доска для серфинга",
    "Sushi": "Суши", "Swan": "Лебедь", "Swim cap": "Шапочка для плавания", "Swimming pool": "Бассейн",
    "Swimwear": "Купальник", "Sword": "Меч", "Syringe": "Шприц", "Table": "Стол",
    "Table tennis racket": "Ракетка для настольного тенниса", "Tablet computer": "Планшет", "Tableware": "Столовая посуда",
    "Taco": "Тако", "Tank": "Танк", "Tap": "Кран", "Tart": "Тарт", "Taxi": "Такси", "Tea": "Чай",
    "Teapot": "Заварочный чайник", "Teddy bear": "Плюшевый мишка", "Telephone": "Телефон", "Television": "Телевизор",
    "Tennis ball": "Теннисный мяч", "Tennis racket": "Теннисная ракетка", "Tent": "Палатка", "Tiara": "Тиара",
    "Tick": "Клещ", "Tie": "Галстук", "Tiger": "Тигр", "Tin can": "Жестяная банка", "Tire": "Шина",
    "Toaster": "Тостер", "Toilet": "Унитаз", "Toilet paper": "Туалетная бумага", "Tomato": "Помидор",
    "Tool": "Инструмент", "Toothbrush": "Зубная щётка", "Torch": "Факел", "Tortoise": "Сухопутная черепаха",
    "Towel": "Полотенце", "Tower": "Башня", "Toy": "Игрушка", "Traffic light": "Светофор",
    "Traffic sign": "Дорожный знак", "Train": "Поезд", "Training bench": "Тренировочная скамья",
    "Treadmill": "Беговая дорожка", "Tree": "Дерево", "Tree house": "Домик на дереве", "Tripod": "Штатив",
    "Trombone": "Тромбон", "Trousers": "Брюки", "Truck": "Грузовик", "Trumpet": "Труба", "Turkey": "Индейка",
    "Turtle": "Черепаха", "Umbrella": "Зонт", "Unicycle": "Моноцикл", "Van": "Фургон", "Vase": "Ваза",
    "Vegetable": "Овощ", "Vehicle": "Транспортное средство", "Vehicle registration plate": "Номерной знак",
    "Violin": "Скрипка", "Volleyball (Ball)": "Волейбольный мяч", "Waffle": "Вафля", "Waffle iron": "Вафельница",
    "Wall clock": "Настенные часы", "Wardrobe": "Шкаф для одежды", "Washing machine": "Стиральная машина",
    "Waste container": "Мусорный контейнер", "Watch": "Наручные часы", "Watercraft": "Плавательное средство",
    "Watermelon": "Арбуз", "Weapon": "Оружие", "Whale": "Кит", "Wheel": "Колесо", "Wheelchair": "Инвалидная коляска",
    "Whisk": "Венчик", "Whiteboard": "Маркерная доска", "Willow": "Ива", "Window": "Окно",
    "Window blind": "Жалюзи", "Wine": "Вино", "Wine glass": "Бокал", "Wine rack": "Винная полка",
    "Winter melon": "Восковая тыква", "Wok": "Вок", "Woman": "Женщина", "Wood-burning stove": "Дровяная печь",
    "Woodpecker": "Дятел", "Worm": "Червь", "Wrench": "Гаечный ключ", "Zebra": "Зебра", "Zucchini": "Цуккини",
}
