"""Русские названия классов COCO (на них обучены стандартные модели YOLO)."""

RU_LABELS = {
    "person": "Человек",
    "bicycle": "Велосипед",
    "car": "Автомобиль",
    "motorcycle": "Мотоцикл",
    "airplane": "Самолёт",
    "bus": "Автобус",
    "train": "Поезд",
    "truck": "Грузовик",
    "boat": "Лодка",
    "traffic light": "Светофор",
    "fire hydrant": "Пожарный гидрант",
    "stop sign": "Знак «Стоп»",
    "parking meter": "Паркомат",
    "bench": "Скамейка",
    "bird": "Птица",
    "cat": "Кошка",
    "dog": "Собака",
    "horse": "Лошадь",
    "sheep": "Овца",
    "cow": "Корова",
    "elephant": "Слон",
    "bear": "Медведь",
    "zebra": "Зебра",
    "giraffe": "Жираф",
    "backpack": "Рюкзак",
    "umbrella": "Зонт",
    "handbag": "Сумка",
    "tie": "Галстук",
    "suitcase": "Чемодан",
    "frisbee": "Фрисби",
    "skis": "Лыжи",
    "snowboard": "Сноуборд",
    "sports ball": "Мяч",
    "kite": "Воздушный змей",
    "baseball bat": "Бейсбольная бита",
    "baseball glove": "Бейсбольная перчатка",
    "skateboard": "Скейтборд",
    "surfboard": "Доска для серфинга",
    "tennis racket": "Теннисная ракетка",
    "bottle": "Бутылка",
    "wine glass": "Бокал",
    "cup": "Чашка",
    "fork": "Вилка",
    "knife": "Нож",
    "spoon": "Ложка",
    "bowl": "Миска",
    "banana": "Банан",
    "apple": "Яблоко",
    "sandwich": "Сэндвич",
    "orange": "Апельсин",
    "broccoli": "Брокколи",
    "carrot": "Морковь",
    "hot dog": "Хот-дог",
    "pizza": "Пицца",
    "donut": "Пончик",
    "cake": "Торт",
    "chair": "Стул",
    "couch": "Диван",
    "potted plant": "Растение в горшке",
    "bed": "Кровать",
    "dining table": "Стол",
    "toilet": "Унитаз",
    "tv": "Телевизор",
    "laptop": "Ноутбук",
    "mouse": "Мышь",
    "remote": "Пульт",
    "keyboard": "Клавиатура",
    "cell phone": "Телефон",
    "microwave": "Микроволновка",
    "oven": "Духовка",
    "toaster": "Тостер",
    "sink": "Раковина",
    "refrigerator": "Холодильник",
    "book": "Книга",
    "clock": "Часы",
    "vase": "Ваза",
    "scissors": "Ножницы",
    "teddy bear": "Плюшевый мишка",
    "hair drier": "Фен",
    "toothbrush": "Зубная щётка",
}


def translate(name: str, lang: str = "ru") -> str:
    """Возвращает название класса на нужном языке (для неизвестных — как есть)."""
    if lang == "ru":
        return RU_LABELS.get(name, name)
    return name
